### ISSUE TITLE
Compatibility with GunGame

### ISSUE THREAD

**Issue by andreiseverin** [rtxa/agmodx#10]
Hello,

I tried all the versions and I can't find one compatible with GunGame for hl. The plugin is working but it doesn't refill the ammo for the weapons. 

```
Currently loaded plugins:
      description      stat pend  file              vers      src   load  unlod
 [ 1] AMX Mod X        RUN   -    amxmodx_mm.dll    v1.9.0.5  ini   Start ANY  
 [ 2] FakeMeta         RUN   -    fakemeta_amxx.dl  v1.9.0.5  pl1   ANY   ANY  
 [ 3] Ham Sandwich     RUN   -    hamsandwich_amxx  v1.9.0.5  pl1   ANY   ANY  
 [ 4] Fun              RUN   -    fun_amxx.dll      v1.9.0.5  pl1   ANY   ANY  
 [ 5] Engine           RUN   -    engine_amxx.dll   v1.9.0.5  pl1   ANY   ANY  
5 plugins, 5 running
] version
Protocol version 48
Exe version 1.1.2.7 (valve)
Exe build: 15:34:33 Jun 15 2009 (4554)
```
Same issue for the BugfixedHL version 1.5.1 . The only version I could find to work is bugfixed.HL.0.1.910. 
So, I think is something wrong in the .dll and .so file (tested on Windows and Linux)

**Comment by rtxa** [comment]
@andreiseverin I'll need to take a look to the code inside of Gungame and test it myself, maybe it has some hardcoded memory offsets (this means that newers versions of HL will not be compatible, not plugin's fault because this is a newer feature in AMXX).

From what I can see, you are using an old version of your HLDS server (4554), the newest one is Build 8xxx, you can download the latest one from SteamCMD, unfortunately I don't have a direct link for that. Try to see if that fixs it.

**Comment by andreiseverin** [comment]
@rtxa 
Here's the link to the gungame plugin > https://forums.alliedmods.net/showthread.php?t=180714
I use that HLDS version on windows to test mods and plugins. It's the New Gause HLDS Server > https://ngageclan.ucoz.ru/load/16-1-0-28
I tested the problem on my linux server witch runs the last version of REHLDS
```
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
ReHLDS version: 3.10.0.760-dev
Build date: 13:06:48 Jun 23 2021 (2629)
Build from: https://github.com/dreamstalker/rehlds/commit/9508c83
```
and it had the same problem.

**Comment by rtxa** [comment]
@andreiseverin Looks like the issue with GunGame was because of the outdated offsets. I think I can close this for now.

I leave here the solution to that issue in case anyone needs it. Thanks to @et-nik

> You can fix offsets in gungame.ini. Change configuration for Half-Life mod in mods -> valve:

```ini
<offsets>
	m_pPlayer = 28
	m_iId = 30
	m_iClip = 40
	m_pActiveItem = 306
	m_rgAmmo = 311
	offsetAmmoDiff = 1
</offsets>
```
