### ISSUE TITLE
undefined symbol "is_user_authorized"

### ISSUE THREAD

**Issue by Safety1st** [rtxa/agmodx#11]
![image](https://user-images.githubusercontent.com/1483401/127668131-f4c0ebce-42a2-4a89-834a-e7d89432a1bc.png)

**Comment by rtxa** [comment]
This is an issue from AMX Mod X mostly, the native it's implemented but the `amxmodx.inc` file doesn't include this. You can workaround this easily by putting in the last line this `native is_user_authorized(id);`

**Comment by Safety1st** [comment]
Placing in the last line doesn't work. You should place the native before using it, before `RestoreScore_FindPlayer()` block.
