### ISSUE TITLE
Update version number

### ISSUE THREAD

**Issue by Safety1st** [rtxa/agmodx#12]
![image](https://user-images.githubusercontent.com/1483401/127716426-77f016d1-6bc4-4d5c-a1fc-48a4f40358d4.png)

**Comment by rtxa** [comment]
Yep, I miss that, I'll fix this in next release and maybe I will create and include or use `agmodx_const.inc` to avoid modifiying like 10 files, instead just one to display the correct version

**Comment by rtxa** [comment]
Fixed in https://github.com/rtxa/agmodx/commit/3a4aaa6b6ae8886898e8f66edf35d8c97ecfdb8e
