### ISSUE TITLE
Clear map after each Arena, LMS and LTS round

### ISSUE THREAD

**Issue by gundogfan** [rtxa/agmodx#15]
Small improvement, but I find it useful (mostly for FPS and aesthetically looks better). The idea is to get rid of decals, bodies and body parts on the floor after each round.

**Comment by rtxa** [comment]
@gundogfan I believe this is not possible without modifying the client. In CS 1.6, you can send the message `ClCorpses` to the client and it will clean the corpses, decals, etc. That doesn't exist in HL.
