### ISSUE TITLE
Host Error

### ISSUE THREAD

**Issue by stefanofabi** [rtxa/agmodx#16]
I get this error when loading agmodx 2.5.1 full for linux.

I have rehlds in its latest version

`
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 03:13:55 Oct 25 2021 (2753)
Server IP address 45.235.98.64:27022
   
   Metamod version 1.21p38 Copyright (c) 2001-2013 Will Day
     Patch: Metamod-P (mm-p) v38 Copyright (c) 2004-2018 Jussi Kivilinna
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
==================
Game DLL version mismatch
DLL version is 140, engine version is 140
The game DLL for valve appears to be outdated, check for updates
==================
Host_Error: 
`

**Comment by stefanofabi** [comment]
Solved, copy hl.so to hl_i386.so

**Comment by rtxa** [comment]
@stefanofabi Good that you have solved the problem. I suppose this problem depends of the Metamod version you use. Some recognizes the game DLL on Linux with the name of `hl_i386.so`. Other versions will be `hl.so`. Previous versions of AG Mod X were using a newer Metamod which I guess that was the source of the problem. Thanks for reporting the issue.
