### ISSUE TITLE
Changing gauss damage behaviour for Instagib

### ISSUE THREAD

**Issue by gundogfan** [rtxa/agmodx#17]
Using Gauss at **_wrong angles_** deals self damage, and since Gauss damage is highly increased in this gamemode it ends up in self kill (even with `mp_selfgauss 0` which doesn't affect in this case). Is it possible to change its behaviour so that this doesn't happen?

**Comment by rtxa** [comment]
This behaviour happens too in the original mod Adrenaline Gamer?

**Comment by gundogfan** [comment]
No idea, I don't play AG.

**Comment by rtxa** [comment]
All right, when I have some time I will check how this behaves in AG, and in any case a CVAR should be added to make it right.

**Comment by Safety1st** [comment]
I have connected idea to improve instagib mode by blocking wallgauss completely. Only direct aiming should kill a player.

**Comment by rtxa** [comment]
I checked and I can confirm the issue which I should fix from inside BugfixedHL. When I find some time I will.

**Comment by rtxa** [comment]
Fixed in version 2.6 with `ag_gauss_fix 2`.
