### ISSUE TITLE
Unable to get agmodx working on pterodactyl

### ISSUE THREAD

**Issue by adrenalinegamer3** [rtxa/agmodx#32]
I've had this working on a windows client correctly, but when I try on a pterodactyl instance I get the following:

[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1705108307
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
Success! App '90' already up to date.
:/home/container$ ./hlds_run -console -game ${HLDS_GAME} -port ${SERVER_PORT} -sport ${VAC_PORT} +map ${SRCDS_MAP} +ip 0.0.0.0 -strictportbind -norestart
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 70
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.2/Stdio (valve)
Exe build: 19:52:19 Aug  3 2020 (8684)
STEAM Auth Server
Server IP address 0.0.0.0:27025
   
   Metamod version 1.21p39 Copyright (c) 2001-2016 Will Day
     Patch: Metamod-P (mm-p) v37 Copyright (c) 2004-2016 Jussi Kivilinna
     Patch: Metamod-P (mm-p) CMake v39 Copyright (c) 2016-2016 Sam Vanheer
   Metamod comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
==================
Game DLL version mismatch
DLL version is 140, engine version is 140
The game DLL for valve appears to be outdated, check for updates
==================
Host_Error: 
FATAL ERROR (shutting down): Host_Error: 
MineCube: Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 255

I'm not sure this version works correctly after the 25th year anniversary. Even when selecting Steam Legacy as my build, this is the results when using the metamod dll's/so's in liblist.gam - Not sure what else to try.

**Comment by rtxa** [comment]
Hi adrenaline, are you using latest version of AG Mod X? I mean version 2.5.2 which is in https://github.com/rtxa/agmodx/releases
If you are using the latest version, please tell me what OS you are using in your server, normally these issues come around with older OS versions and the best option would be to update, anyway it should work because I'm using an older version of Linux too.

**Comment by utharper** [comment]
Hey, by a very weird coincidence I had the same problem today, and I'm also using Pterodactyl to manage my servers.

In my case it worked after uploading **hl.so** from the latest commit https://github.com/rtxa/agmodx/commit/b4606bd90f7670eefff380532f52efbf94f0a5bc, this was a few days after the latest release package.
If you're using ReHLDS, it seems to require `steam_legacy`, otherwise not.

**Comment by adrenalinegamer3** [comment]
> Hi adrenaline, are you using latest version of AG Mod X? I mean version 2.5.2 which is in https://github.com/rtxa/agmodx/releases If you are using the latest version, please tell me what OS you are using in your server, normally these issues come around with older OS versions and the best option would be to update, anyway it should work because I'm using an older version of Linux too.

To answer this - Latest version yes. The server is running Ubuntu 22.04 LTS also running Pterodactyl on top of it to host servers.



> Hey, by a very weird coincidence I had the same problem today, and I'm also using Pterodactyl to manage my servers.
> 
> In my case it worked after uploading **hl.so** from the latest commit [b4606bd](https://github.com/rtxa/agmodx/commit/b4606bd90f7670eefff380532f52efbf94f0a5bc), this was a few days after the latest release package. If you're using ReHLDS, it seems to require `steam_legacy`, otherwise not.

I will give this a shot and see, this is probably it as it was complaining the file was out of date.

**Comment by adrenalinegamer3** [comment]
That last commit file worked to get the server loading, but now I see two more issues. No matter what I try, I cannot vote game modes like arcade, arena, etc etc? I also cannot get this server public either. I can use the same port for an AG server, but it's not working for this. Is there an additional lan command for this?

**Comment by adrenalinegamer3** [comment]
That last commit file worked to get the server loading, but now no matter what I try, I cannot vote game modes like arcade, arena, etc etc?

**Comment by rtxa** [comment]
> Hey, by a very weird coincidence I had the same problem today, and I'm also using Pterodactyl to manage my servers.
> 
> In my case it worked after uploading **hl.so** from the latest commit [b4606bd](https://github.com/rtxa/agmodx/commit/b4606bd90f7670eefff380532f52efbf94f0a5bc), this was a few days after the latest release package. If you're using ReHLDS, it seems to require `steam_legacy`, otherwise not.

Oh, I forgot that the working hl.so was in the latest commit, thanks for pointing it out.

About the new changes of 25th anniversary, I'm not sure if AG Mod X is working fine with latest HLDS/ReHLDS version, I'll need to do some test.

I should be uploading a new version before the end of the month with the new features and I'll try to look into this.

**Comment by adrenalinegamer3** [comment]
> > Hey, by a very weird coincidence I had the same problem today, and I'm also using Pterodactyl to manage my servers.
> > In my case it worked after uploading **hl.so** from the latest commit [b4606bd](https://github.com/rtxa/agmodx/commit/b4606bd90f7670eefff380532f52efbf94f0a5bc), this was a few days after the latest release package. If you're using ReHLDS, it seems to require `steam_legacy`, otherwise not.
> 
> Oh, I forgot that the working hl.so was in the latest commit, thanks for pointing it out.
> 
> About the new changes of 25th anniversary, I'm not sure if AG Mod X is working fine with latest HLDS/ReHLDS version, I'll need to do some test.
> 
> I should be uploading a new version before the end of the month with the new features and I'll try to look into this.

Thank you for getting back to me on this. Glad to hear a new version will be out. I will wait patiently, ty. At least for now my server is running, easy to fix later.

**Comment by adrenalinegamer3** [comment]
> There's no issues as far as I could tell with the latest HLDS, or reHLDS with _steam_legacy_. I tried both but switched to ReHLDS to fix the problem of the game mode not updating in server browser. (I guess it probably fixes some other things as well)
> 
> I use Pterodactyl on Debian 12, so we should have very similar setups. Here is the particular egg script I used: https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/hlds_server
> 
> * After importing, I also edited the script to repeat the installation command 3 times (classic steamcmd problem with GoldSrc games).
> 
> Maybe you can try a fresh install with this script, then upload the mod files, plus the newer hl.so. In my case this is working great now.

Could you happen to copy and paste what you used?

**Comment by utharper** [comment]
> > There's no issues as far as I could tell with the latest HLDS, or reHLDS with _steam_legacy_. I tried both but switched to ReHLDS to fix the problem of the game mode not updating in server browser. (I guess it probably fixes some other things as well)
> > I use Pterodactyl on Debian 12, so we should have very similar setups. Here is the particular egg script I used: https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/hlds_server
> > 
> > * After importing, I also edited the script to repeat the installation command 3 times (classic steamcmd problem with GoldSrc games).
> > 
> > Maybe you can try a fresh install with this script, then upload the mod files, plus the newer hl.so. In my case this is working great now.
> 
> Could you happen to copy and paste what you used?
I copied the steamcmd command on **line 32** and pasted it to repeat 3 times. That's the only change I've made to the install script. There's a common problem with steamcmd where it fails to properly install the game files on the first try. I don't know if this is relevant to your problem, but a fresh installation is advisable

**Comment by rtxa** [comment]
I would like to point out that AG Mod X relies in hook_cvar_change() which according to some folks from the AMXX Discord group, ReHLDS is being affected by this issue and signatures need to be changed for Cvar_DirectSet.
![imagen](https://github.com/rtxa/agmodx/assets/25672911/4f917fc6-cd8d-46e2-8395-acb4706591ea)

**Comment by rtxa** [comment]
Fixed by updating BugfixedHL to support older Linux versiones with `GLIBC 2.17`. Still, I should consider dropping support for older version because of being unsafe.
