### ISSUE TITLE
AG Mod X not working

### ISSUE THREAD

**Issue by rootmapavri** [rtxa/agmodx#33]
[ 16] NextMap                 1.9.0.5294  AMXX Dev Team     nextmap.amxx     running  
 [ 17] Nextmap Chooser         1.9.0.5294  AMXX Dev Team     mapchooser.amxx  running  
 [ 18] TimeLeft                1.9.0.5294  AMXX Dev Team     timeleft.amxx    running  
 [ 19] Pause Plugins           1.9.0.5294  AMXX Dev Team     pausecfg.amxx    running  
 [ 20] Stats Configuration     1.9.0.5294  AMXX Dev Team     statscfg.amxx    running  
 [ 21] AG Mod X                Beta 2.5.2  rtxA              agmodx.amxx      debug    
 [ 22] AG Mod X Arcade         Beta 2.5.2  rtxA              agmodx_arcade.a  stopped  

 I installed the plugin and updated everything but it doesn't work.

**Comment by rootmapavri** [comment]
agmodx works but this time I can't run arcade.amxx

**Comment by rtxa** [comment]
What makes you think AG Mod X doesn't work? If it's because agmodx_arcade.amxx says stopped it's completely normal because only runs when the gamemode is set in Arcade, otherwise it will not run. Different would be that you are in Arcade mode and isn't working neither.

**Comment by rootmapavri** [comment]
thank you problem solved
